language: ruby
rvm:
  - ruby
before_script:
  - phantomjs --version
env:
  - PHANTOMJS_VERSION=2.1.1
cache:
  directories:
    - "travis_phantomjs"
before_install:
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
  - gem install bundler
script:
  - bundle exec rake test_app
  - bundle exec rake
matrix:
  include:
  - rvm: ruby
    gemfile: gemfiles/opal_0.10_react_15.gemfile
  allow_failures:
  - rvm: ruby
    gemfile: gemfiles/opal_master_react_15.gemfile
