dist: trusty
language: ruby
rvm:
  - ruby
env:
  - DRIVER=travis HYPER_DEV_GEM_SOURCE="https://gems.ruby-hyperloop.org" TZ=Europe/Berlin
  - DRIVER=beheaded HYPER_DEV_GEM_SOURCE="https://gems.ruby-hyperloop.org" TZ=Europe/Berlin
before_install:
  - if [[ "$DRIVER" == "travis" ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
  - if [[ "$DRIVER" == "travis" ]]; then sudo dpkg -i google-chrome*.deb; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then tar zxf geckodriver-v0.19.1-linux64.tar.gz; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then sudo mv geckodriver /usr/local/bin/; fi
  - gem install bundler
before_script:
  - cd spec/test_app
  - bundle update
  - bundle exec rails db:setup
  - cd ../../
  - if [[ "$DRIVER" == "travis" ]]; then chromedriver-update; fi
  - if [[ "$DRIVER" == "travis" ]]; then ls -lR ~/.chromedriver-helper/; fi
  - if [[ "$DRIVER" == "travis" ]]; then chromedriver --version; fi
  - if [[ "$DRIVER" == "travis" ]]; then google-chrome --version; fi
  - if [[ "$DRIVER" == "travis" ]]; then which chromedriver; fi
  - if [[ "$DRIVER" == "travis" ]]; then which google-chrome; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then firefox --version; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then geckodriver --version; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then which firefox; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then which geckodriver; fi
script: bundle exec rspec
gemfile:
  - gemfiles/opal_0_11_react-rails_2_4.gemfile
