language: ruby
rvm:
  - ruby
env:
  - HYPER_DEV_GEM_SOURCE="https://gems.ruby-hyperloop.org" TZ=Europe/Berlin
before_install:
  - sudo apt-get install -y fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - gem install bundler
before_script:
  - chromedriver-update
  - ls -lR ~/.chromedriver-helper/
script:
  - bundle exec rake test_app
  - bundle exec rake test
gemfile:
  - gemfiles/opal_0_10_react-rails_2_3.gemfile
  - gemfiles/opal_0_10_react-rails_2_4.gemfile
  - gemfiles/opal_0_11_react-rails_2_4.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/opal_0_11_react-rails_2_4.gemfile
